version: '3'

services:
  django:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./staticfiles:/app/staticfiles/
      - ./mediafiles:/app/media/
      - bundles_volume:/app/bundles/
    depends_on:
      - postgres
    env_file:
      - .env
    command: >
      sh -c "python /app/manage.py migrate &&
             python /app/manage.py collectstatic --noinput &&
             python /app/manage.py runserver 0.0.0.0:8000"
    expose:
      - 8000
    ports:
      - 8000:8000
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - bundles_volume:/app/frontend/bundles/

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
    restart: always

#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./staticfiles/:/code/static
#      - ./media/:/code/media
#      - ./nginx_config/:/etc/nginx/conf.d/
#    depends_on:
#      - django
#    restart: always

volumes:
  postgres_data:
  bundles_volume:
