# Generated by Django 3.2.15 on 2023-11-09 07:38

from django.db import migrations


def calculate_price_for_old_orders(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    orders = Order.objects.all()
    for order in orders.iterator():
        for order_item in order.order_items.all().iterator():
            order_item.price = order_item.product.price
            order_item.save(update_fields=['price'])


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_alter_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(calculate_price_for_old_orders),
    ]
