# Generated by Django 3.2.15 on 2023-11-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UN', 'Необработанный'), ('AD', 'Принят'), ('RE', 'Готовят'), ('TC', 'Передан курьеру'), ('CO', 'Выполнен')], db_index=True, default='UN', max_length=2),
        ),
    ]
