# Generated by Django 3.2.15 on 2023-11-09 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20231109_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CA', 'Наличными'), ('EL', 'Электронно')], db_index=True, default='EL', max_length=2, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='call_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата звонка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registration_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания заказа'),
        ),
    ]
