# Generated by Django 3.2.15 on 2023-11-23 07:37
import requests
from django.db import migrations
from django.utils import timezone

from restaurateur.service import fetch_coordinates
from star_burger.settings import YANDEX_GEOCODER_TOKEN


def create_place(place_model, address):
    try:
        coordinate = fetch_coordinates(YANDEX_GEOCODER_TOKEN, address)
        if coordinate:
            lng, lat = coordinate
        else:
            lng, lat = None, None
        geocoding_failed = False
    except requests.RequestException:
        lng, lat = None, None
        geocoding_failed = True

    place_model.objects.get_or_create(
        address=address,
        defaults={
            'geocoding_failed': geocoding_failed,
            'lng': lng,
            'lat': lat,
            'date': timezone.localtime()
        }
    )


def create_places(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    Restaurant = apps.get_model('foodcartapp', 'Restaurant')
    Place = apps.get_model('places', 'Place')

    for order in Order.objects.all().iterator():
        create_place(Place, order.address)

    for restaurant in Restaurant.objects.all().iterator():
        create_place(Place, restaurant.address)


def move_backward(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    Place.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_geocoding_failed'),
    ]

    operations = [
        migrations.RunPython(create_places, move_backward),
    ]
